test:
  runs-on: ubuntu-latest

  services:
    mysql:
      image: mysql:8.0
      env:
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_DATABASE: test_db
      ports:
        - 3306:3306
      options: --health-cmd="mysqladmin ping -prootpassword" --health-interval=10s --health-timeout=5s --health-retries=5

  steps:
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential default-libmysqlclient-dev git libyaml-dev pkg-config

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true

    - name: Setup DB (create + schema load)
      env:
        RAILS_ENV: test
        DATABASE_URL: mysql2://root:rootpassword@127.0.0.1:3306/test_db
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_URL: mysql2://root:rootpassword@127.0.0.1:3306/test_db
      run: bundle exec rails test
